"""Sonic eye geometry, in SVG user units.

GENERATED by scripts/extract_eye_geometry.py from art/sonic-eyes.svg.
Do not edit by hand; edit the art file and re-run the script.

Every Inkscape transform is already baked into these coordinates, so the
shapes can be dropped into an <svg> as-is. The contour is the white of both
eyes as a single outline; each iris is black and carries a white shine that
must travel with it when the gaze moves.
"""

# Tight bounding box of the contour: (min_x, min_y, width, height).
CONTOUR_BBOX = (-203.7640, -163.5298, 141.3925, 82.3255)

# Centre of that box. The runtime transform pins this to the middle of the panel.
CONTOUR_CENTER = (-133.0677, -122.3670)

CONTOUR_PATH = (
    "M-182.3873,-163.4826C-151.3873,-164.4826,-161.2724,-104.1386,-134.3873,-103.4826C-106.3759,-102.7991,-109.3349,-165.4917,-81.3873,-163.4826C-69.2841,-162.6125,-61.9838,-146.6103,-62.3873,-134.4826C-63.1600,-111.2553,-74.8655,-91.2527,-96.3873,-82.4826C-107.2054,-78.0742,-128.3873,-86.4826,-135.3873,-86.4826C-142.3873,-86.4826,-147.3873,-81.4826,-163.3873,-81.4826C-187.4081,-81.4826,-200.5790,-103.3778,-203.3873,-123.4826C-205.5747,-139.1426,-198.1912,-162.9728,-182.3873,-163.4826z"
)

IRISES = [
        {"cx": -158.5697, "cy": -111.1424, "rx": 6.4507, "ry": 19.8881, "rot": 0.4282},
        {"cx": -111.0000, "cy": -111.0000, "rx": 6.4507, "ry": 19.8881, "rot": 5.3082},
]

SHINES = [
        {"cx": -157.3366, "cy": -118.0712, "rx": 2.4009, "ry": 7.7512, "rot": 4.4321},
        {"cx": -110.7568, "cy": -116.9048, "rx": 2.4009, "ry": 7.7512, "rot": 4.6084},
]
